vich_uploader:
    db_driver: orm

    mappings:
        event_image:
           uri_prefix: /images/event_image
           upload_destination: '%kernel.project_dir%/public/images/event_image'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true



        classifiedAd_image:
           uri_prefix: /images/classifiedAd_image
           upload_destination: '%kernel.project_dir%/public/images/classifiedAd_image'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true